### ISSUE TITLE
urdf for EP

### ISSUE THREAD

**Issue by zhuhaier1992** [jukindle/robomaster_ros#2]
Hi Jukindle, your repo is really helpful, thank you very much! 
I noticed there is S1 urdf but no EP urdf, could you upload it if you have it, or could you share the method by which you obtained the S1 urdf, so I can manage to obtain that for EP?

**Comment by jukindle** [comment]
Hi! As described in the [robomaster_description README](https://github.com/jukindle/robomaster_ros/tree/main/robomaster_description), I got the mesh model from [sketchfab](https://sketchfab.com/3d-models/robomaster-s1-finchtest-3aaf212833a34b6fb8e12a661082d8a0). I used Meshlab to cut the model into pieces and then manually wrote the URDF. Unfortunately, I am unable to find a 3D model for the EP version - at least the base is equivalent, right? Maybe you're more lucky and find a 3D model for the end-effector and can stitch it together. If so, let me know if you need more help.

**Comment by zhuhaier1992** [comment]
Thank you very much for your prompt reply! I am just beginning to learn all about ROS2. If I managed to implement EP model later, I will come back to comment. Thanks again! :)
